services:
  jenkins:
    build: 
      context: .
      dockerfile: Dockerfile
    image: jenkins-demo:latest
    container_name: jenkins
    ports:
      - "8080:8080"
      - "50000:50000"
    volumes:
      - jenkins_home:/var/jenkins_home
      - /var/run/docker.sock:/var/run/docker.sock
    user: "jenkins"
    restart: unless-stopped
volumes:
  jenkins_home: